#!/bin/bash

CAT="MAM"
blastdbcmd -entry all -ctrl_a -db nt | python ../../bin/db_splitter.py ../../bin/nt_headers $CAT | makeblastdb -title "nt."$CAT -parse_seqids -out ../nt.split/"nt."$CAT -dbtype nucl -taxid_map ../../taxdb/gi_taxid_nucl.dmp 2> $CAT".log"

CAT="BCT"
blastdbcmd -entry all -ctrl_a -db nt | python ../../bin/db_splitter.py ../../bin/nt_headers $CAT | makeblastdb -title "nt."$CAT -parse_seqids -out ../nt.split/"nt."$CAT -dbtype nucl -taxid_map ../../taxdb/gi_taxid_nucl.dmp 2> $CAT".log"

CAT="VRL"
blastdbcmd -entry all -ctrl_a -db nt | python ../../bin/db_splitter.py ../../bin/nt_headers $CAT | makeblastdb -title "nt."$CAT -parse_seqids -out ../nt.split/"nt."$CAT -dbtype nucl -taxid_map ../../taxdb/gi_taxid_nucl.dmp 2> $CAT".log"

CAT="OTR"
blastdbcmd -entry all -ctrl_a -db nt | python ../../bin/db_splitter.py ../../bin/nt_headers $CAT | makeblastdb -title "nt."$CAT -parse_seqids -out ../nt.split/"nt."$CAT -dbtype nucl -taxid_map ../../taxdb/gi_taxid_nucl.dmp 2> $CAT".log"
