#!/bin/sh
clear
wget ftp://ftp.ncbi.nih.gov/blast/db/nr.*tar.gz

echo ""
echo "Extracting files..."
ls nr.*tar.gz | while read FILE
do
        echo "$FILE"
        tar -zxf $FILE
        rm $FILE
done
