#!/bin/sh
clear
wget ftp://ftp.ncbi.nih.gov/blast/db/human_genomic.*tar.gz

echo ""
echo "Extracting files..."
ls human_genomic.*tar.gz | while read FILE
do
        echo "$FILE"
        tar -xzf $FILE
        rm $FILE
done
